apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: crossplane-demo-vpc
spec:
  forProvider:
    region: us-west-1
    cidrBlock: 192.167.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    tags:
    - key: Environment
      value: Production
    - key: Owner
      value: sabin
    - key: Name
      value: crossplane-demo-vpc
    instanceTenancy: default
  providerConfigRef:
    name: default
